[package]
name = "hyprland-toplevel-export-streamer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bitflags = "2.10.0"
libc = "0.2.177"
wayland-backend = "0.3.11"
wayland-client = "0.31.11"
wayland-scanner = "0.31.7"
